### ISSUE TITLE
Интеграция. Шаблон

### ISSUE THREAD

**Issue by vak1n** [Kirill1001/bitrix#1]
Создадим шаблон для нашего будущего сайта.

Необходимо создать для нового шаблона отдельную папку, куда добавить необходимые папки и файлы. В шапке и подвале разместить соответствующую html разметку, подключить стили и скрипты. Применить созданный шаблон к сайту, без каких либо условий.

Важный момент, логотип в шапке должен быть ссылкой на главную на всех страницах кроме самой главной.

**Comment by Kirill1001** [comment]
Создал шаблон и сделал соответствующие настройки

**Comment by Kirill1001** [comment]
Удалил картинки и ненужные файлы
